version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/library"
      - "/packages/*"
      - "/website"
      - "/codemod/*"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    commit-message:
      prefix: "dependabot"
    groups:
      npm-deps:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "saturday"
      time: "09:00"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "dependabot"
    groups:
      github-actions:
        patterns:
          - '*'

