name: Setup environment
description: Setup environment with Node.js, Deno and pnpm

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: Setup npm
      shell: bash
      run: npm install --global npm@11.11.1

    - name: Setup Deno
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
      with:
        deno-version: v2.5.6

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Build library
      shell: bash
      run: pnpm build
      working-directory: library

    - name: Build to-json-schema
      shell: bash
      run: pnpm build
      working-directory: packages/to-json-schema

    - name: Build zod-to-valibot
      shell: bash
      run: pnpm build
      working-directory: codemod/zod-to-valibot
